ALTER TABLE EMPLOYEES
    DROP COLUMN NOTES
    DROP COLUMN PHOTO
    DROP COLUMN REPORTSTO;

    ALTER TABLE PRODUCTS
    DROP CONSTRAINT SUPPLIERS_ID;
    ALTER TABLE PRODUCTS
    ADD CONSTRAINT PHONE_PK FOREIGN KEY (PHONE_ID) REFERENCES SUPPLITERS;
    ALTER TABLE SUPPLITERS
    DROP CONSTRAINT SUPPLITERS_PK;
    ALTER TABLE SUPPLITERS
    ADD CONSTRAINT PHONE_PK PRIMARY KEY (PHONE);

    ALTER TABLE CUSTOMER
    ADD IS_ACTIVE NUMBER DEFAULT 0 CHECK (IS_ACTIVE = 0 OR IS_ACTIVE = 1);

    ALTER TABLE CATEGORIES
    MODIFY PICTURE NVARCHAR2(100);

    CREATE SEQUENCE MY_FIRST_SEQUENCE
    START WITH 1
    INCREMENT BY 3;